2018/10/28 21:48:13 [error] 7#7: *9 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "127.0.0.1:8080"
2018/10/29 08:32:28 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:32:29 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:32:30 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:32:30 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:32:49 [error] 6#6: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:32:49 [error] 6#6: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:32:50 [error] 6#6: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:32:50 [error] 6#6: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:32:50 [error] 6#6: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:32:51 [error] 6#6: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:32:51 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:32:51 [error] 6#6: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:33:43 [error] 6#6: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:33:43 [error] 6#6: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:34:21 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:34:21 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:34:22 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:34:23 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:34:23 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:34:23 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:34:23 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:34:24 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:34:24 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:34:24 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:37:06 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:37:07 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:37:07 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:37:08 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:37:08 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:37:08 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:37:08 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:37:08 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:37:09 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:37:09 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:37:09 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:38:53 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:38:53 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:38:54 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:38:54 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:39:02 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:43:48 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:43:49 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:43:50 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:43:50 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:43:51 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:43:51 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:45:39 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:45:39 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:45:39 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:45:40 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:45:40 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:45:40 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
2018/10/29 08:45:40 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:45:40 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080"
2018/10/29 08:45:40 [error] 10#10: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.4:9001", host: "symfony.localhost:8080", referrer: "http://symfony.localhost:8080/"
